# конфигурационный файл с настройками исключений и уровней

exclude_rules:
  - rule_id_1
  - rule_id_2
severity_threshold: MEDIUM # интересуют ошибки уровня MEDIUM и выше

# Пути для сканирования
scan_paths:
  - ./src
  - ./tests

